# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
# - Multiple values [false, true] assigned to 'jdbc.maps.K2'. Values are merged into a yaml sequence node.
jdbc:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql:///subharghya
  username: root
  password: admin
  numbers:
  - 10
  - 20
  - 30
  integers: 100,200,300
  names:
  - ina
  - mina
  - tika
  - mina
  maps:
    K1: true
    K2: false
  config:
    name: Anya
    roll: 2002

