spring:
  datasource:
    url: jdbc:mysql:///sbms_2024
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
