spring:
  datasource:
    url: jdbc:mysql:///subharghya
#    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: oracle.jdbc.OracleDriver
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
